name: markets

services:
  order_service:
    build:
      context: ..
      dockerfile: ./cmd/order_service/v1/Dockerfile
    hostname: order_service
    environment:
      REDIS_ADDR: $REDIS_ADDR
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_USER: $REDIS_USER
      REDIS_DB: $REDIS_DB
      REDIS_MAX_RETRIES: $REDIS_MAX_RETRIES
      REDIS_RW_TIMEOUT: $REDIS_RW_TIMEOUT
    ports:
      - "8888:8888"
    links:
      - "spot_instrument"
      - "redis"
      - "jaeger"
    depends_on:
      - spot_instrument
      - redis
      - jaeger
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2

  spot_instrument:
    build:
      context: ..
      dockerfile: ./cmd/spot_instrument/v1/Dockerfile
    hostname: spot_instrument
    environment:
      REDIS_ADDR: $REDIS_ADDR
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_USER: $REDIS_USER
      REDIS_DB: $REDIS_DB
      REDIS_MAX_RETRIES: $REDIS_MAX_RETRIES
      REDIS_RW_TIMEOUT: $REDIS_RW_TIMEOUT
    ports:
      - "9999:9999"
    restart: always
    links:
      - "redis"
      - "jaeger"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2

  metrics_prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../config/metrics/prometheus:/etc/prometheus

  redis:
    image: redis:latest
    container_name: redis_cache_container
    hostname: redis_cache
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_USER: $REDIS_USER
      REDIS_USER_PASSWORD: $REDIS_USER_PASSWORD
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      bash -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    ports:
      - "16686:16686" # web iface
      - "14268:14268" # collector
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: 2

