name: markets

services:
  order_service:
    build:
      context: ..
      dockerfile: ./cmd/order_service/v1/Dockerfile
    hostname: order_service
    ports:
      - "8888:8888"
    links:
      - "spot_instrument"
    depends_on:
      - spot_instrument
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2

  spot_instrument:
    build:
      context: ..
      dockerfile: ./cmd/spot_instrument/v1/Dockerfile
    hostname: spot_instrument
    ports:
      - "9999:9999"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2

  metrics_prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../config/metrics/prometheus:/etc/prometheus

  # jaeger:
  #   image: jaegertracing/all-in-one
  #   ports:
  #     - "16686:16686" # web iface
  #     - "14268:14268" # collector
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: 2
